# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: .:Roderick Rodriguez - Technology:.
#email: your-email@domain.com
description: > # My name is Roderick Rodriguez, during the day I am a Software Engineer. I build cool software using the Agile/Scrum processes and work on the full stack.  This site is dedicated to all things technology related.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rodrod.github.io" # the base hostname & protocol for your site
github_username:  rodrod

# Build settings
markdown: kramdown
